apiVersion: v2
name: drone
description: Drone is a self-service Continuous Delivery platform for busy development teams

type: application

sources:
- https://github.com/drone/drone
- https://github.com/drone/helm

version: 0.1.0

appVersion: "1.9.0"
