env:
  DRONE_SERVER_HOST: drone.127-0-0-1.nip.io
  DRONE_SERVER_PROTO: http
  DRONE_RPC_SECRET: randomly-generated-secret-here

  DRONE_GITHUB_CLIENT_ID: 301dcfe14b70d5f6fe95
  DRONE_GITHUB_CLIENT_SECRET: 79002e67273c142cec31e223664176eb7bd5b2c9

ingress:
  enabled: true
  hosts:
    - host: drone.127-0-0-1.nip.io
      paths:
        - path: /
          pathType: ImplementationSpecific