---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mechanicalbot-gitops/gitops
    targetRevision: HEAD
    path: argocd
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated: {}
