---
apiVersion: v1
kind: Secret
metadata:
  name: react-docker
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/mechanicalbot-gitops/react-docker
